CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`country` varchar(100) NOT NULL,
	`city` varchar(100) NOT NULL,
	`sector` varchar(100) NOT NULL,
	`currentRole` varchar(200) NOT NULL,
	`yearsExperience` int NOT NULL,
	`programmingLevel` enum('none','beginner','intermediate','advanced','expert') NOT NULL,
	`aiKnowledge` enum('none','basic','intermediate','advanced','expert') NOT NULL,
	`cloudExperience` enum('none','basic','intermediate','advanced','expert') NOT NULL,
	`technicalTools` text,
	`certifications` text,
	`sectorExpertise` enum('junior','intermediate','senior','expert') NOT NULL,
	`clientNetwork` enum('none','small','medium','large') NOT NULL,
	`businessDevelopment` enum('none','basic','intermediate','advanced') NOT NULL,
	`languages` text,
	`publicSpeaking` enum('none','basic','intermediate','advanced') NOT NULL,
	`salesExperience` enum('none','less_1y','1_3y','3_5y','more_5y') NOT NULL,
	`motivation` text NOT NULL,
	`scoreTechnique` decimal(5,2) NOT NULL,
	`scoreMetier` decimal(5,2) NOT NULL,
	`scoreCommunication` decimal(5,2) NOT NULL,
	`scoreTotal` decimal(5,2) NOT NULL,
	`status` enum('en_attente','selectionne','refuse') NOT NULL DEFAULT 'en_attente',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`)
);
