import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

const value = (item: unknown, lang: string) => {
  if (typeof item === "string") return item;
  if (item && typeof item === "object") return (item as Record<string, string>)[lang] || (item as Record<string, string>).fr || (item as Record<string, string>).en || "";
  return "";
};

export function NovasavoLearningBlock({ block, lang, onComplete, courseId, lessonTitle, screenTitle }: { block: any; lang: string; onComplete: (id: string) => void; courseId?: string; lessonTitle?: string; screenTitle?: string }) {
  const [answer, setAnswer] = useState<string | null>(null);
  const [notes, setNotes] = useState("");
  const [bookmarked, setBookmarked] = useState(false);
  const [assistantQuestion, setAssistantQuestion] = useState("");
  const assistantMutation = trpc.courseAssistant.ask.useMutation();
  const title = value(block.title, lang);
  const body = value(block.body || block.description, lang);
  const options = useMemo(() => (block.options || []).map((option: any) => ({ ...option, label: value(option.text || option.label, lang) })), [block.options, lang]);
  const complete = (selected: string) => { setAnswer(selected); onComplete(block.id || block.type); };
  const correct = answer !== null && answer === block.correctAnswer;

  if (block.type === "unit_hero_blue") return <section className="overflow-hidden rounded-2xl bg-gradient-to-br from-blue-600 via-blue-600 to-indigo-700 p-7 text-white md:p-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-100">Finance & Comptabilité · Unité {block.unitNumber}/12</p><h1 className="mt-4 max-w-3xl text-3xl font-extrabold leading-tight md:text-5xl">{title}</h1><p className="mt-4 max-w-2xl text-lg text-blue-50">{body}</p><div className="mt-7 flex items-center gap-3 text-sm font-semibold text-blue-100"><span>≈ {block.duration || "20 min"}</span><span className="h-1 w-20 rounded-full bg-white/40" /><span>Progression séquentielle</span></div></section>;
  if (block.type === "learning_objectives_panel") return <section className="grid gap-5 rounded-2xl border border-border bg-card p-6 md:grid-cols-[180px_1fr]"><h2 className="text-xl font-bold text-foreground">Cette unité va vous apporter</h2><ul className="space-y-3">{(block.items || []).map((item: any, index: number) => <li key={index} className="flex gap-3 text-sm leading-relaxed text-muted-foreground"><span className="font-bold text-primary">{String(index + 1).padStart(2, "0")}</span><span>{value(item, lang)}</span></li>)}</ul></section>;
  if (block.type === "inline_myth_reality") return <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Mythe ou réalité ? · +{block.xp || 5} XP</p><h2 className="mt-3 text-xl font-bold text-foreground">{value(block.prompt, lang)}</h2><div className="mt-5 grid grid-cols-2 gap-3"><Button variant={answer === "mythe" ? "default" : "outline"} onClick={() => complete("mythe")}>Mythe</Button><Button variant={answer === "realite" ? "default" : "outline"} onClick={() => complete("realite")}>Réalité</Button></div>{answer && <div className={`mt-5 rounded-xl p-4 text-sm ${correct ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-950"}`}><strong>{correct ? "Correct." : "À retenir."}</strong> {value(block.explanation, lang)}</div>}</section>;
  if (block.type === "inline_multiple_choice_feedback" || block.type === "inline_scenario_question_feedback") return <section className={`rounded-2xl p-6 text-white ${block.type === "inline_scenario_question_feedback" ? "bg-slate-950" : "bg-gradient-to-br from-indigo-700 to-blue-700"}`}><p className="text-xs font-bold uppercase tracking-wider text-blue-200">{block.type === "inline_scenario_question_feedback" ? "Scénario" : "Exercice · Choix multiple"} · +{block.xp || 10} XP</p><h2 className="mt-3 text-xl font-bold leading-relaxed">{value(block.prompt || block.scenario, lang)}</h2><div className="mt-5 space-y-3">{options.map((option: any) => <button type="button" key={option.id} onClick={() => complete(option.id)} className={`w-full rounded-xl border p-4 text-left text-sm font-medium transition-colors ${answer === option.id ? "border-blue-300 bg-white/15" : "border-white/15 bg-white/5 hover:bg-white/10"}`}><span className="mr-3 text-blue-200">{option.id?.toUpperCase()}.</span>{option.label}</button>)}</div>{answer && <div className={`mt-5 rounded-xl p-4 text-sm ${correct ? "bg-emerald-500/20 text-emerald-100" : "bg-amber-300/15 text-amber-100"}`}><strong>{correct ? "Bonne réponse." : "Réponse enregistrée."}</strong> {value(block.explanation, lang)}</div>}</section>;
  if (block.type === "timeline_step_cards") return <section className="rounded-2xl border border-border bg-card p-6"><h2 className="text-xl font-bold">{title}</h2><ol className="mt-5 grid gap-3 md:grid-cols-2">{(block.steps || []).map((step: any, index: number) => <li key={index} className="rounded-xl bg-muted p-4"><p className="font-bold text-primary">{index + 1}. {value(step.title || step, lang)}</p>{step.description && <p className="mt-2 text-sm text-muted-foreground">{value(step.description, lang)}</p>}</li>)}</ol></section>;
  if (block.type === "process_flow_diagram") return <section className="rounded-2xl border border-border bg-card p-6"><h2 className="text-xl font-bold">{title}</h2><div className="mt-5 flex flex-wrap items-center gap-2">{(block.nodes || []).map((node: any, index: number) => <><span key={`node-${index}`} className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-950">{value(node, lang)}</span>{index < (block.nodes || []).length - 1 && <span key={`arrow-${index}`} className="text-primary">→</span>}</>)}</div></section>;
  if (block.type === "mistake_correction_pairs") return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="text-xl font-bold">{title || "Erreurs fréquentes"}</h2><div className="mt-4 space-y-3">{(block.pairs || []).map((pair: any, index: number) => <div key={index} className="grid gap-3 rounded-xl bg-white p-4 md:grid-cols-2"><p className="text-sm text-rose-700"><strong>À éviter : </strong>{value(pair.mistake, lang)}</p><p className="text-sm text-emerald-800"><strong>À faire : </strong>{value(pair.correction, lang)}</p></div>)}</div></section>;
  if (block.type === "ai_assistant_prompt_panel") {
    const context = value(block.prompt, lang) || body;
    const ask = () => {
      if (!assistantQuestion.trim() || !courseId || !lessonTitle || !screenTitle) return;
      assistantMutation.mutate({ courseId: "automatisation_comptable_ia__01", lessonTitle, screenTitle, context, question: assistantQuestion.trim() });
    };
    return <section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-blue-300">Demandez à votre assistant</p><h2 className="mt-2 text-xl font-bold">{title}</h2><p className="mt-4 rounded-xl bg-white/10 p-4 text-sm leading-relaxed text-slate-100">{context}</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={() => navigator.clipboard?.writeText(context)}>Copier le prompt</Button><Button variant="outline" onClick={() => setAssistantQuestion("Peux-tu donner un exemple simple et rappeler le contrôle humain à conserver ?")}>Question suggérée</Button></div><div className="mt-4 flex gap-2"><input value={assistantQuestion} onChange={(event) => setAssistantQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") ask(); }} className="min-w-0 flex-1 rounded-lg border border-white/20 bg-white px-3 py-2 text-sm text-slate-950" placeholder="Posez une autre question…" /><Button disabled={!assistantQuestion.trim() || !courseId || assistantMutation.isPending} onClick={ask}>{assistantMutation.isPending ? "Réponse…" : "Demander"}</Button></div>{assistantMutation.data?.answer && <div className="mt-4 rounded-xl border border-blue-300/30 bg-blue-500/10 p-4 text-sm leading-relaxed text-blue-50"><strong className="text-blue-200">Assistant pédagogique</strong><p className="mt-1 whitespace-pre-wrap">{assistantMutation.data.answer}</p></div>}{assistantMutation.error && <p className="mt-3 text-sm text-rose-200">Réponse indisponible. Utilisez le prompt avec un assistant autorisé par votre organisation.</p>}</section>;
  }
  if (block.type === "notes_highlights_bookmarks_panel") return <section className="rounded-2xl border border-border bg-card p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Mes notes</h2><p className="text-sm text-muted-foreground">Conservez vos points clés pendant cette lecture.</p></div><Button variant={bookmarked ? "default" : "outline"} onClick={() => setBookmarked((current) => !current)}>{bookmarked ? "Signet ajouté" : "Ajouter un signet"}</Button></div><textarea value={notes} onChange={(event) => setNotes(event.target.value)} className="mt-4 min-h-28 w-full rounded-xl border border-input bg-background p-3 text-sm" placeholder="Écrivez une note personnelle…" /></section>;
  if (block.type === "xp_progress_hud") return <section className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-blue-200 bg-blue-50 p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Progression</p><p className="mt-1 font-semibold">Validez les activités obligatoires pour débloquer l’écran suivant.</p></div><div className="rounded-full bg-white px-4 py-2 text-sm font-bold text-primary">+{block.xp || 15} XP possibles</div></section>;
  if (block.type === "course_completion_next_unit_panel") return <section className="rounded-2xl bg-emerald-700 p-6 text-white"><h2 className="text-2xl font-bold">Unité prête à être terminée</h2><p className="mt-2 text-emerald-50">Terminez l’activité ci-dessus puis passez à l’unité suivante.</p></section>;
  return null;
}
