import type { TrainingVisualAsset } from "./trainingVisualAssets";

/** Assets générés à partir du template de marque pour chaque formation. */
export const GENERATED_TRAINING_VISUAL_ASSETS: Record<string, TrainingVisualAsset> = {
  "claude_certified_architect_foundations": {
    socialPath: "/manus-storage/claude_certified_architect_foundations-social_472f8615.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_architect_foundations-card_28b1cb51.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Architect – Fondations", en: "Claude Certified Architect – Fondations", ar: "Claude Certified Architect – Fondations" },
  },
  "claude_certified_architect_professional": {
    socialPath: "/manus-storage/claude_certified_architect_professional-social_abb98cb3.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_architect_professional-card_fb98f07e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Architect – Professionnel", en: "Claude Certified Architect – Professionnel", ar: "Claude Certified Architect – Professionnel" },
  },
  "claude_certified_associate_foundations": {
    socialPath: "/manus-storage/claude_certified_associate_foundations-social_d89c547c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_associate_foundations-card_9e2f534a.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Associate – Fondations", en: "Claude Certified Associate – Fondations", ar: "Claude Certified Associate – Fondations" },
  },
  "claude_certified_developer_foundations": {
    socialPath: "/manus-storage/claude_certified_developer_foundations-social_3930fac1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_developer_foundations-card_a5ba96f1.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Developer – Fondations", en: "Claude Certified Developer – Fondations", ar: "Claude Certified Developer – Fondations" },
  },
  "analyse_donnees_reporting_bi_codex": {
    socialPath: "/manus-storage/analyse_donnees_reporting_bi_codex-social_a1608b04.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/analyse_donnees_reporting_bi_codex-card_bdfaeb8b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Analyse de données, reporting et BI avec Codex", en: "Analyse de données, reporting et BI avec Codex", ar: "Analyse de données, reporting et BI avec Codex" },
  },
  "datacamp_ai_for_data_analysts": {
    socialPath: "/manus-storage/datacamp_ai_for_data_analysts-social_670be927.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_data_analysts-card_eeed9c5f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour les data analysts", en: "L’IA pour les data analysts", ar: "L’IA pour les data analysts" },
  },
  "datacamp_ai_for_finance": {
    socialPath: "/manus-storage/datacamp_ai_for_finance-social_7c4d83d1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_finance-card_04850c6a.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour la finance", en: "L’IA pour la finance", ar: "L’IA pour la finance" },
  },
  "datacamp_building_marketing_workflows_with_n8n": {
    socialPath: "/manus-storage/datacamp_building_marketing_workflows_with_n8n-social_ad03f713.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_marketing_workflows_with_n8n-card_75c965f2.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des workflows marketing automatisés", en: "Concevoir des workflows marketing automatisés", ar: "Concevoir des workflows marketing automatisés" },
  },
  "datacamp_intermediate_workflow_automation_with_n8n": {
    socialPath: "/manus-storage/datacamp_intermediate_workflow_automation_with_n8n-social_6e3bbb6f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_intermediate_workflow_automation_with_n8n-card_906cecda.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Automatisation de workflows avancée", en: "Automatisation de workflows avancée", ar: "Automatisation de workflows avancée" },
  },
  "initiation_automatisation_workflows_n8n": {
    socialPath: "/manus-storage/initiation_automatisation_workflows_n8n-social_1a207520.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/initiation_automatisation_workflows_n8n-card_a73086b0.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Initiation à l’automatisation de workflows", en: "Initiation à l’automatisation de workflows", ar: "Initiation à l’automatisation de workflows" },
  },
  "ai_finops_cost_engineering_specialist": {
    socialPath: "/manus-storage/ai_finops_cost_engineering_specialist-social_22012214.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_finops_cost_engineering_specialist-card_136487c9.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI FinOps and Cost Engineering Specialist", en: "AI FinOps and Cost Engineering Specialist", ar: "AI FinOps and Cost Engineering Specialist" },
  },
  "ai_governance_compliance_responsible_ai_leader": {
    socialPath: "/manus-storage/ai_governance_compliance_responsible_ai_leader-social_293a69a9.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_governance_compliance_responsible_ai_leader-card_1e0467fc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Governance, Compliance and Responsible AI Leader", en: "AI Governance, Compliance and Responsible AI Leader", ar: "AI Governance, Compliance and Responsible AI Leader" },
  },
  "ai_product_management_human_centered_ux_specialist": {
    socialPath: "/manus-storage/ai_product_management_human_centered_ux_specialist-social_59a10c52.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_product_management_human_centered_ux_specialist-card_03cd8eb3.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Product Management and Human-Centered UX Specialist", en: "AI Product Management and Human-Centered UX Specialist", ar: "AI Product Management and Human-Centered UX Specialist" },
  },
  "ia_pour_les_nuls": {
    socialPath: "/manus-storage/ia_pour_les_nuls-social_76ec4be4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_pour_les_nuls-card_702595d6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA pour les nuls – Initiation", en: "IA pour les nuls – Initiation", ar: "IA pour les nuls – Initiation" },
  },
  "datacamp_building_scalable_agentic_systems": {
    socialPath: "/manus-storage/datacamp_building_scalable_agentic_systems-social_e88b2df6.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_scalable_agentic_systems-card_27940ad6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des systèmes agentiques évolutifs", en: "Concevoir des systèmes agentiques évolutifs", ar: "Concevoir des systèmes agentiques évolutifs" },
  },
  "datacamp_claude_101": {
    socialPath: "/manus-storage/datacamp_claude_101-social_ffecc602.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_claude_101-card_be87c89b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude 101", en: "Claude 101", ar: "Claude 101" },
  },
  "datacamp_claude_code_101": {
    socialPath: "/manus-storage/datacamp_claude_code_101-social_cbb030d0.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_claude_code_101-card_d470e663.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Code 101", en: "Claude Code 101", ar: "Claude Code 101" },
  },
  "datacamp_claude_code_in_action": {
    socialPath: "/manus-storage/datacamp_claude_code_in_action-social_c7ed6e28.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_claude_code_in_action-card_f4c80fd9.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Code en action", en: "Claude Code en action", ar: "Claude Code en action" },
  },
  "datacamp_introduction_to_agent_skills": {
    socialPath: "/manus-storage/datacamp_introduction_to_agent_skills-social_964bc9c0.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_agent_skills-card_16f39de5.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux Agent Skills", en: "Introduction aux Agent Skills", ar: "Introduction aux Agent Skills" },
  },
  "datacamp_introduction_to_claude_models": {
    socialPath: "/manus-storage/datacamp_introduction_to_claude_models-social_a6bbd46f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_claude_models-card_d98d668c.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux modèles Claude", en: "Introduction aux modèles Claude", ar: "Introduction aux modèles Claude" },
  },
  "datacamp_introduction_to_subagents": {
    socialPath: "/manus-storage/datacamp_introduction_to_subagents-social_0ede0cc6.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_subagents-card_aae25bf2.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux sous-agents", en: "Introduction aux sous-agents", ar: "Introduction aux sous-agents" },
  },
  "datacamp_model_context_protocol_advanced_topics": {
    socialPath: "/manus-storage/datacamp_model_context_protocol_advanced_topics-social_982c7654.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_model_context_protocol_advanced_topics-card_cfb0bb13.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Sujets avancés sur le Model Context Protocol", en: "Sujets avancés sur le Model Context Protocol", ar: "Sujets avancés sur le Model Context Protocol" },
  },
  "datacamp_software_development_with_claude_code": {
    socialPath: "/manus-storage/datacamp_software_development_with_claude_code-social_6ac72ca3.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_software_development_with_claude_code-card_00ef2e2f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développement logiciel avec Claude Code", en: "Développement logiciel avec Claude Code", ar: "Développement logiciel avec Claude Code" },
  },
  "transformation_processus_ia": {
    socialPath: "/manus-storage/transformation_processus_ia-social_544fd6b9.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/transformation_processus_ia-card_4de9bca9.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Transformation des Processus par l'IA", en: "Transformation des Processus par l'IA", ar: "Transformation des Processus par l'IA" },
  },
  "novasavo_automatisation_comptable_ia": {
    socialPath: "/manus-storage/novasavo_automatisation_comptable_ia-social_7e56ef91.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/novasavo_automatisation_comptable_ia-card_4601437d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Automatisation comptable par l’IA", en: "Automatisation comptable par l’IA", ar: "Automatisation comptable par l’IA" },
  },
  "advanced_rag_evaluation_specialist": {
    socialPath: "/manus-storage/advanced_rag_evaluation_specialist-social_dddddf54.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/advanced_rag_evaluation_specialist-card_476a6645.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Advanced RAG and Evaluation Specialist", en: "Advanced RAG and Evaluation Specialist", ar: "Advanced RAG and Evaluation Specialist" },
  },
  "ai_data_engineering_rag_practitioner": {
    socialPath: "/manus-storage/ai_data_engineering_rag_practitioner-social_55f4de39.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_data_engineering_rag_practitioner-card_e1006fbb.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Data Engineering and RAG Practitioner", en: "AI Data Engineering and RAG Practitioner", ar: "AI Data Engineering and RAG Practitioner" },
  },
  "ai_production_infrastructure_model_serving_engineer": {
    socialPath: "/manus-storage/ai_production_infrastructure_model_serving_engineer-social_2731b953.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_production_infrastructure_model_serving_engineer-card_f4c20772.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Production Infrastructure and Model Serving Engineer", en: "AI Production Infrastructure and Model Serving Engineer", ar: "AI Production Infrastructure and Model Serving Engineer" },
  },
  "datacamp_advanced_ai_assisted_coding_for_developers": {
    socialPath: "/manus-storage/datacamp_advanced_ai_assisted_coding_for_developers-social_aab7ac21.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_advanced_ai_assisted_coding_for_developers-card_6b98dbfe.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Programmation assistée par IA avancée pour les développeurs", en: "Programmation assistée par IA avancée pour les développeurs", ar: "Programmation assistée par IA avancée pour les développeurs" },
  },
  "datacamp_ai_agents_with_hugging_face_smolagents": {
    socialPath: "/manus-storage/datacamp_ai_agents_with_hugging_face_smolagents-social_f4b8f3b4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_agents_with_hugging_face_smolagents-card_4480a882.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des agents IA avec smolagents", en: "Concevoir des agents IA avec smolagents", ar: "Concevoir des agents IA avec smolagents" },
  },
  "datacamp_ai_assisted_coding_for_developers": {
    socialPath: "/manus-storage/datacamp_ai_assisted_coding_for_developers-social_d4b52d1f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_assisted_coding_for_developers-card_b2f6a042.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Coder avec l’aide de l’IA pour les développeurs", en: "Coder avec l’aide de l’IA pour les développeurs", ar: "Coder avec l’aide de l’IA pour les développeurs" },
  },
  "datacamp_ai_for_marketing": {
    socialPath: "/manus-storage/datacamp_ai_for_marketing-social_b6a278a4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_marketing-card_dcfe29c1.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA pour le marketing", en: "IA pour le marketing", ar: "IA pour le marketing" },
  },
  "datacamp_ai_for_sales": {
    socialPath: "/manus-storage/datacamp_ai_for_sales-social_69e19e86.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_sales-card_87fadcc2.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour les ventes", en: "L’IA pour les ventes", ar: "L’IA pour les ventes" },
  },
  "datacamp_building_agentic_workflows_with_llamaindex": {
    socialPath: "/manus-storage/datacamp_building_agentic_workflows_with_llamaindex-social_1f48c5c1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_agentic_workflows_with_llamaindex-card_ab69df84.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Créer des workflows agentiques avec LlamaIndex", en: "Créer des workflows agentiques avec LlamaIndex", ar: "Créer des workflows agentiques avec LlamaIndex" },
  },
  "datacamp_building_ai_agents_with_crewai": {
    socialPath: "/manus-storage/datacamp_building_ai_agents_with_crewai-social_fe84b3ba.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_ai_agents_with_crewai-card_7f28eb65.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Créer des agents d’IA avec CrewAI", en: "Créer des agents d’IA avec CrewAI", ar: "Créer des agents d’IA avec CrewAI" },
  },
  "datacamp_building_ai_agents_with_haystack": {
    socialPath: "/manus-storage/datacamp_building_ai_agents_with_haystack-social_fa75d0f8.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_ai_agents_with_haystack-card_18533ef8.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Créer des agents d’IA avec Haystack", en: "Créer des agents d’IA avec Haystack", ar: "Créer des agents d’IA avec Haystack" },
  },
  "datacamp_databricks_with_the_python_sdk": {
    socialPath: "/manus-storage/datacamp_databricks_with_the_python_sdk-social_0b9dc029.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_databricks_with_the_python_sdk-card_5b77d69f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Databricks avec le SDK Python", en: "Databricks avec le SDK Python", ar: "Databricks avec le SDK Python" },
  },
  "datacamp_deploying_ai_into_production_with_fastapi": {
    socialPath: "/manus-storage/datacamp_deploying_ai_into_production_with_fastapi-social_b1446723.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_deploying_ai_into_production_with_fastapi-card_1a779d46.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Déployer l’IA en production avec FastAPI", en: "Déployer l’IA en production avec FastAPI", ar: "Déployer l’IA en production avec FastAPI" },
  },
  "datacamp_efficient_ai_model_training_with_pytorch": {
    socialPath: "/manus-storage/datacamp_efficient_ai_model_training_with_pytorch-social_9f7b1acc.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_efficient_ai_model_training_with_pytorch-card_c42e7357.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Entraîner efficacement des modèles d’IA avec PyTorch", en: "Entraîner efficacement des modèles d’IA avec PyTorch", ar: "Entraîner efficacement des modèles d’IA avec PyTorch" },
  },
  "datacamp_end_to_end_rag_with_weaviate": {
    socialPath: "/manus-storage/datacamp_end_to_end_rag_with_weaviate-social_c98bfd0d.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_end_to_end_rag_with_weaviate-card_44022d83.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "RAG de bout en bout avec Weaviate", en: "RAG de bout en bout avec Weaviate", ar: "RAG de bout en bout avec Weaviate" },
  },
  "datacamp_graph_rag_with_langchain_and_neo4j": {
    socialPath: "/manus-storage/datacamp_graph_rag_with_langchain_and_neo4j-social_8d71c8e3.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_graph_rag_with_langchain_and_neo4j-card_8ce97238.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Graph RAG avec LangChain et Neo4j", en: "Graph RAG avec LangChain et Neo4j", ar: "Graph RAG avec LangChain et Neo4j" },
  },
  "datacamp_innovating_with_google_cloud_ai": {
    socialPath: "/manus-storage/datacamp_innovating_with_google_cloud_ai-social_fbb760b1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_innovating_with_google_cloud_ai-card_07062b4e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Innover avec Google Cloud AI", en: "Innover avec Google Cloud AI", ar: "Innover avec Google Cloud AI" },
  },
  "datacamp_introduction_to_generative_ai_in_snowflake": {
    socialPath: "/manus-storage/datacamp_introduction_to_generative_ai_in_snowflake-social_e6871841.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_generative_ai_in_snowflake-card_8febf525.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA générative dans Snowflake", en: "IA générative dans Snowflake", ar: "IA générative dans Snowflake" },
  },
  "datacamp_introduction_to_model_context_protocol_mcp": {
    socialPath: "/manus-storage/datacamp_introduction_to_model_context_protocol_mcp-social_b7001e5e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_model_context_protocol_mcp-card_cba67e88.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction au Model Context Protocol (MCP)", en: "Introduction au Model Context Protocol (MCP)", ar: "Introduction au Model Context Protocol (MCP)" },
  },
  "datacamp_multi_agent_systems_with_langgraph": {
    socialPath: "/manus-storage/datacamp_multi_agent_systems_with_langgraph-social_1025e19f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_multi_agent_systems_with_langgraph-card_7db5c6cc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Systèmes multi-agents avec LangGraph", en: "Systèmes multi-agents avec LangGraph", ar: "Systèmes multi-agents avec LangGraph" },
  },
  "datacamp_multi_modal_models_with_hugging_face": {
    socialPath: "/manus-storage/datacamp_multi_modal_models_with_hugging_face-social_7ce52fdf.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_multi_modal_models_with_hugging_face-card_fda58563.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des modèles multimodaux", en: "Concevoir des modèles multimodaux", ar: "Concevoir des modèles multimodaux" },
  },
  "datacamp_scalable_ai_models_with_pytorch_lightning": {
    socialPath: "/manus-storage/datacamp_scalable_ai_models_with_pytorch_lightning-social_c848a4cf.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_scalable_ai_models_with_pytorch_lightning-card_f4464bdc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Modèles d’IA évolutifs avec PyTorch Lightning", en: "Modèles d’IA évolutifs avec PyTorch Lightning", ar: "Modèles d’IA évolutifs avec PyTorch Lightning" },
  },
  "datacamp_software_development_with_github_copilot": {
    socialPath: "/manus-storage/datacamp_software_development_with_github_copilot-social_68c90702.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_software_development_with_github_copilot-card_7f29f0b2.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développement logiciel avec GitHub Copilot", en: "Développement logiciel avec GitHub Copilot", ar: "Développement logiciel avec GitHub Copilot" },
  },
  "datacamp_software_development_with_windsurf": {
    socialPath: "/manus-storage/datacamp_software_development_with_windsurf-social_0ba45a5e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_software_development_with_windsurf-card_a8fde4e4.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développement logiciel avec Windsurf", en: "Développement logiciel avec Windsurf", ar: "Développement logiciel avec Windsurf" },
  },
  "datacamp_text_to_query_agents_with_mongodb_and_langgraph": {
    socialPath: "/manus-storage/datacamp_text_to_query_agents_with_mongodb_and_langgraph-social_696952ef.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_text_to_query_agents_with_mongodb_and_langgraph-card_e398c13a.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agents de text-to-query avec MongoDB et LangGraph", en: "Agents de text-to-query avec MongoDB et LangGraph", ar: "Agents de text-to-query avec MongoDB et LangGraph" },
  },
  "datacamp_vibe_coding_with_replit": {
    socialPath: "/manus-storage/datacamp_vibe_coding_with_replit-social_e01ab3b9.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_vibe_coding_with_replit-card_cc7a8aec.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Coder en mode Vibe avec Replit", en: "Coder en mode Vibe avec Replit", ar: "Coder en mode Vibe avec Replit" },
  },
  "full_stack_ai_application_developer": {
    socialPath: "/manus-storage/full_stack_ai_application_developer-social_c03f7001.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/full_stack_ai_application_developer-card_df64af47.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Full-Stack AI Application Developer", en: "Full-Stack AI Application Developer", ar: "Full-Stack AI Application Developer" },
  },
  "huggingface_llm_course": {
    socialPath: "/manus-storage/huggingface_llm_course-social_7fb6ef4d.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/huggingface_llm_course-card_0dfa3618.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Fondamentaux des grands modèles de langage", en: "Fondamentaux des grands modèles de langage", ar: "Fondamentaux des grands modèles de langage" },
  },
  "llm_application_security_red_teaming_specialist": {
    socialPath: "/manus-storage/llm_application_security_red_teaming_specialist-social_9925f90b.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/llm_application_security_red_teaming_specialist-card_55441984.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "LLM Application Security and Red Teaming Specialist", en: "LLM Application Security and Red Teaming Specialist", ar: "LLM Application Security and Red Teaming Specialist" },
  },
  "llmops_ai_observability_engineer": {
    socialPath: "/manus-storage/llmops_ai_observability_engineer-social_dd3b7ef8.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/llmops_ai_observability_engineer-card_bdc0f73e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "LLMOps and AI Observability Engineer", en: "LLMOps and AI Observability Engineer", ar: "LLMOps and AI Observability Engineer" },
  },
  "open_source_llms_fine_tuning_engineer": {
    socialPath: "/manus-storage/open_source_llms_fine_tuning_engineer-social_d5ee64ee.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/open_source_llms_fine_tuning_engineer-card_d1edd919.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Open-Source LLMs and Fine-Tuning Engineer", en: "Open-Source LLMs and Fine-Tuning Engineer", ar: "Open-Source LLMs and Fine-Tuning Engineer" },
  },
  "datacamp_developing_ai_systems_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_developing_ai_systems_with_the_openai_api-social_6c1c17c6.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_developing_ai_systems_with_the_openai_api-card_1055fc14.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développer des systèmes d’IA avec l’API OpenAI", en: "Développer des systèmes d’IA avec l’API OpenAI", ar: "Développer des systèmes d’IA avec l’API OpenAI" },
  },
  "datacamp_introduction_to_embeddings_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_introduction_to_embeddings_with_the_openai_api-social_3170d4d1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_embeddings_with_the_openai_api-card_8acddc2e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux embeddings avec l’API OpenAI", en: "Introduction aux embeddings avec l’API OpenAI", ar: "Introduction aux embeddings avec l’API OpenAI" },
  },
  "datacamp_multi_modal_systems_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_multi_modal_systems_with_the_openai_api-social_e4b59fd6.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_multi_modal_systems_with_the_openai_api-card_66f42ea2.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Systèmes multimodaux avec l’API OpenAI", en: "Systèmes multimodaux avec l’API OpenAI", ar: "Systèmes multimodaux avec l’API OpenAI" },
  },
  "datacamp_prompt_engineering_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_prompt_engineering_with_the_openai_api-social_2c759abb.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_prompt_engineering_with_the_openai_api-card_883d4e5f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Prompt Engineering avec l’API OpenAI", en: "Prompt Engineering avec l’API OpenAI", ar: "Prompt Engineering avec l’API OpenAI" },
  },
  "datacamp_working_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_working_with_the_openai_api-social_4295e6a5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_working_with_the_openai_api-card_e780cccc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Travailler avec l’API OpenAI", en: "Travailler avec l’API OpenAI", ar: "Travailler avec l’API OpenAI" },
  },
  "datacamp_working_with_the_openai_responses_api": {
    socialPath: "/manus-storage/datacamp_working_with_the_openai_responses_api-social_8d4c03de.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_working_with_the_openai_responses_api-card_fe78c8d3.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Utiliser l’API OpenAI Responses", en: "Utiliser l’API OpenAI Responses", ar: "Utiliser l’API OpenAI Responses" },
  },
  "ia_appliquee_metiers_tp__formation_01": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_01-social_31390b3e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_01-card_d0f95a49.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de prospection Google Maps avec scoring automatique", en: "Agent de prospection Google Maps avec scoring automatique", ar: "Agent de prospection Google Maps avec scoring automatique" },
  },
  "ia_appliquee_metiers_tp__formation_02": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_02-social_fc6b7ec6.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_02-card_182ad5d4.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent IA de qualification automatique des leads", en: "Agent IA de qualification automatique des leads", ar: "Agent IA de qualification automatique des leads" },
  },
  "ia_appliquee_metiers_tp__formation_03": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_03-social_f9592938.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_03-card_9604108e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent d'enrichissement et qualification automatique dans HubSpot", en: "Agent d'enrichissement et qualification automatique dans HubSpot", ar: "Agent d'enrichissement et qualification automatique dans HubSpot" },
  },
  "ia_appliquee_metiers_tp__formation_04": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_04-social_49f3a882.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_04-card_638a32c9.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Assistant IA permettant d'interroger HubSpot en langage naturel", en: "Assistant IA permettant d'interroger HubSpot en langage naturel", ar: "Assistant IA permettant d'interroger HubSpot en langage naturel" },
  },
  "ia_appliquee_metiers_tp__formation_05": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_05-social_a40412a5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_05-card_3a159e85.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Prospection quotidienne automatisée avec e-mails personnalisés", en: "Prospection quotidienne automatisée avec e-mails personnalisés", ar: "Prospection quotidienne automatisée avec e-mails personnalisés" },
  },
  "ia_appliquee_metiers_tp__formation_06": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_06-social_81a04550.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_06-card_cd72e72f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de génération automatique de propositions commerciales", en: "Agent de génération automatique de propositions commerciales", ar: "Agent de génération automatique de propositions commerciales" },
  },
  "ia_appliquee_metiers_tp__formation_07": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_07-social_eda7f5ba.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_07-card_7b1f07ae.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Équipe de trois agents pour LinkedIn, X et Instagram", en: "Équipe de trois agents pour LinkedIn, X et Instagram", ar: "Équipe de trois agents pour LinkedIn, X et Instagram" },
  },
  "ia_appliquee_metiers_tp__formation_08": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_08-social_f4f0d593.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_08-card_5739dfa6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent transformant les commentaires sociaux en stratégie de contenu", en: "Agent transformant les commentaires sociaux en stratégie de contenu", ar: "Agent transformant les commentaires sociaux en stratégie de contenu" },
  },
  "ia_appliquee_metiers_tp__formation_09": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_09-social_67b987b0.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_09-card_9e87507d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent qui analyse les contenus viraux puis publie automatiquement", en: "Agent qui analyse les contenus viraux puis publie automatiquement", ar: "Agent qui analyse les contenus viraux puis publie automatiquement" },
  },
  "ia_appliquee_metiers_tp__formation_10": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_10-social_cf1d86ba.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_10-card_df901c2b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agence SEO autonome composée de plusieurs agents", en: "Agence SEO autonome composée de plusieurs agents", ar: "Agence SEO autonome composée de plusieurs agents" },
  },
  "ia_appliquee_metiers_tp__formation_11": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_11-social_1cc584a4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_11-card_13c9a260.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un agent de support client avec Make.com", en: "Construire un agent de support client avec Make.com", ar: "Construire un agent de support client avec Make.com" },
  },
  "ia_appliquee_metiers_tp__formation_12": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_12-social_9aa6f06e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_12-card_288bffa6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir un agent IA de support client", en: "Concevoir un agent IA de support client", ar: "Concevoir un agent IA de support client" },
  },
  "ia_appliquee_metiers_tp__formation_13": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_13-social_589f7e35.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_13-card_3c9a9ba7.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Chatbot de site web capable de lire le site et la documentation", en: "Chatbot de site web capable de lire le site et la documentation", ar: "Chatbot de site web capable de lire le site et la documentation" },
  },
  "ia_appliquee_metiers_tp__formation_14": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_14-social_8000ea80.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_14-card_eb73d6dc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent Zendesk RAG avec base documentaire et mémoire", en: "Agent Zendesk RAG avec base documentaire et mémoire", ar: "Agent Zendesk RAG avec base documentaire et mémoire" },
  },
  "ia_appliquee_metiers_tp__formation_15": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_15-social_b88e8f4f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_15-card_d3fddb65.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent e-commerce connecté aux commandes et stocks", en: "Agent e-commerce connecté aux commandes et stocks", ar: "Agent e-commerce connecté aux commandes et stocks" },
  },
  "ia_appliquee_metiers_tp__formation_16": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_16-social_6957dd4c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_16-card_c178311a.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Piloter Shopify directement par conversation", en: "Piloter Shopify directement par conversation", ar: "Piloter Shopify directement par conversation" },
  },
  "ia_appliquee_metiers_tp__formation_17": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_17-social_6a0b2ad4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_17-card_f55874dd.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un agent de tenue comptable", en: "Construire un agent de tenue comptable", ar: "Construire un agent de tenue comptable" },
  },
  "ia_appliquee_metiers_tp__formation_18": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_18-social_a6a26a0a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_18-card_b1aa5917.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de traitement de factures - tutoriel français", en: "Agent de traitement de factures - tutoriel français", ar: "Agent de traitement de factures - tutoriel français" },
  },
  "ia_appliquee_metiers_tp__formation_19": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_19-social_4d5814b3.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_19-card_a5fbc856.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Comptabilisation automatique des factures reçues dans Google Drive", en: "Comptabilisation automatique des factures reçues dans Google Drive", ar: "Comptabilisation automatique des factures reçues dans Google Drive" },
  },
  "ia_appliquee_metiers_tp__formation_20": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_20-social_62f5473c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_20-card_24b41173.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Facturation et relances automatiques des impayés", en: "Facturation et relances automatiques des impayés", ar: "Facturation et relances automatiques des impayés" },
  },
  "ia_appliquee_metiers_tp__formation_21": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_21-social_fdb8efb9.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_21-card_902d8945.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Reporting financier mensuel avec détection d'anomalies", en: "Reporting financier mensuel avec détection d'anomalies", ar: "Reporting financier mensuel avec détection d'anomalies" },
  },
  "ia_appliquee_metiers_tp__formation_22": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_22-social_24ebcbfa.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_22-card_65889d74.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent capable de traiter et classer 1 000 CV", en: "Agent capable de traiter et classer 1 000 CV", ar: "Agent capable de traiter et classer 1 000 CV" },
  },
  "ia_appliquee_metiers_tp__formation_23": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_23-social_9baa24ae.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_23-card_146c8237.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Recrutement avec agents spécialisés selon le poste", en: "Recrutement avec agents spécialisés selon le poste", ar: "Recrutement avec agents spécialisés selon le poste" },
  },
  "ia_appliquee_metiers_tp__formation_24": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_24-social_2d724f0a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_24-card_cc315add.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Présélection et entretien comportemental réalisé par un Voice Agent", en: "Présélection et entretien comportemental réalisé par un Voice Agent", ar: "Présélection et entretien comportemental réalisé par un Voice Agent" },
  },
  "ia_appliquee_metiers_tp__formation_25": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_25-social_c5eb2d30.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_25-card_9251759a.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Screening des candidats puis planification automatique des entretiens", en: "Screening des candidats puis planification automatique des entretiens", ar: "Screening des candidats puis planification automatique des entretiens" },
  },
  "ia_appliquee_metiers_tp__formation_26": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_26-social_3963833c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_26-card_a5e4c587.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Automatiser l'onboarding collaborateur avec Jira, Notion et Gmail", en: "Automatiser l'onboarding collaborateur avec Jira, Notion et Gmail", ar: "Automatiser l'onboarding collaborateur avec Jira, Notion et Gmail" },
  },
  "ia_appliquee_metiers_tp__formation_27": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_27-social_60f2d55c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_27-card_a01ff2ff.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent IA qui gère complètement une boîte Gmail", en: "Agent IA qui gère complètement une boîte Gmail", ar: "Agent IA qui gère complètement une boîte Gmail" },
  },
  "ia_appliquee_metiers_tp__formation_28": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_28-social_1d595d26.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_28-card_448f5bef.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir un agent d’assistance par e-mail", en: "Concevoir un agent d’assistance par e-mail", ar: "Concevoir un agent d’assistance par e-mail" },
  },
  "ia_appliquee_metiers_tp__formation_29": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_29-social_6ce6f598.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_29-card_a50e83a4.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Transformer des notes vocales Telegram en tâches Notion", en: "Transformer des notes vocales Telegram en tâches Notion", ar: "Transformer des notes vocales Telegram en tâches Notion" },
  },
  "ia_appliquee_metiers_tp__formation_30": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_30-social_77f231e5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_30-card_64ebef97.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Assistant exécutif Telegram avec Gmail, Calendar et Notion", en: "Assistant exécutif Telegram avec Gmail, Calendar et Notion", ar: "Assistant exécutif Telegram avec Gmail, Calendar et Notion" },
  },
  "ia_appliquee_metiers_tp__formation_31": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_31-social_86cef1da.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_31-card_33632037.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Compte rendu de réunion vers décisions, tâches Linear et Slack", en: "Compte rendu de réunion vers décisions, tâches Linear et Slack", ar: "Compte rendu de réunion vers décisions, tâches Linear et Slack" },
  },
  "ia_appliquee_metiers_tp__formation_32": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_32-social_afe66f64.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_32-card_4717f8fc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un Data Analyst IA conversationnel", en: "Construire un Data Analyst IA conversationnel", ar: "Construire un Data Analyst IA conversationnel" },
  },
  "ia_appliquee_metiers_tp__formation_33": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_33-social_678097db.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_33-card_360081f6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Interroger une base MySQL en langage naturel", en: "Interroger une base MySQL en langage naturel", ar: "Interroger une base MySQL en langage naturel" },
  },
  "ia_appliquee_metiers_tp__formation_34": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_34-social_4e02f7de.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_34-card_5163358f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un agent de recherche Web avec Perplexity", en: "Construire un agent de recherche Web avec Perplexity", ar: "Construire un agent de recherche Web avec Perplexity" },
  },
  "ia_appliquee_metiers_tp__formation_35": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_35-social_eb7c8bf5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_35-card_78b515a5.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent RAG pour analyser les résultats financiers d'entreprises", en: "Agent RAG pour analyser les résultats financiers d'entreprises", ar: "Agent RAG pour analyser les résultats financiers d'entreprises" },
  },
  "ia_appliquee_metiers_tp__formation_36": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_36-social_becab807.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_36-card_802b15c0.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent permettant de dialoguer avec les fichiers Drive et Supabase", en: "Agent permettant de dialoguer avec les fichiers Drive et Supabase", ar: "Agent permettant de dialoguer avec les fichiers Drive et Supabase" },
  },
  "ia_appliquee_metiers_tp__formation_37": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_37-social_2e747f3a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_37-card_5959c83c.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent qui compare les clauses d'un contrat à votre playbook juridique", en: "Agent qui compare les clauses d'un contrat à votre playbook juridique", ar: "Agent qui compare les clauses d'un contrat à votre playbook juridique" },
  },
  "ia_appliquee_metiers_tp__formation_38": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_38-social_4e37d82b.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_38-card_b5293f9e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Système multi-agents de revue contractuelle et conformité réglementaire", en: "Système multi-agents de revue contractuelle et conformité réglementaire", ar: "Système multi-agents de revue contractuelle et conformité réglementaire" },
  },
  "ia_appliquee_metiers_tp__formation_39": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_39-social_d7413826.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_39-card_93c380a0.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Analyse automatique des risques d'un contrat PDF", en: "Analyse automatique des risques d'un contrat PDF", ar: "Analyse automatique des risques d'un contrat PDF" },
  },
  "ia_appliquee_metiers_tp__formation_40": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_40-social_90e6d2b8.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_40-card_0a74a852.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de classification et routage de documents juridiques", en: "Agent de classification et routage de documents juridiques", ar: "Agent de classification et routage de documents juridiques" },
  },
  "datacamp_ai_for_consulting": {
    socialPath: "/manus-storage/datacamp_ai_for_consulting-social_bcaa3037.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_consulting-card_3ca5eac5.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour le conseil", en: "L’IA pour le conseil", ar: "L’IA pour le conseil" },
  },
  "datacamp_ai_for_human_resources": {
    socialPath: "/manus-storage/datacamp_ai_for_human_resources-social_10a7cdfd.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_human_resources-card_c8ccfd49.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour les ressources humaines", en: "L’IA pour les ressources humaines", ar: "L’IA pour les ressources humaines" },
  },
  "datacamp_gemini_in_gmail": {
    socialPath: "/manus-storage/datacamp_gemini_in_gmail-social_d6a66bbf.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_gmail-card_9804680d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Gmail", en: "Gemini dans Gmail", ar: "Gemini dans Gmail" },
  },
  "datacamp_gemini_in_google_docs": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_docs-social_55cbb008.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_docs-card_f5d006b8.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Docs", en: "Gemini dans Google Docs", ar: "Gemini dans Google Docs" },
  },
  "datacamp_gemini_in_google_drive": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_drive-social_caad8fc1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_drive-card_6def8722.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Drive", en: "Gemini dans Google Drive", ar: "Gemini dans Google Drive" },
  },
  "datacamp_gemini_in_google_meet": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_meet-social_6b532b7e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_meet-card_f8717be3.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Meet", en: "Gemini dans Google Meet", ar: "Gemini dans Google Meet" },
  },
  "datacamp_gemini_in_google_sheets": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_sheets-social_d1ac7955.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_sheets-card_ef25417b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Sheets", en: "Gemini dans Google Sheets", ar: "Gemini dans Google Sheets" },
  },
  "datacamp_gemini_in_google_slides": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_slides-social_fd11dfa8.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_slides-card_41beeb2d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Slides", en: "Gemini dans Google Slides", ar: "Gemini dans Google Slides" },
  },
  "datacamp_introduction_to_ai_for_work": {
    socialPath: "/manus-storage/datacamp_introduction_to_ai_for_work-social_ee05d920.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_ai_for_work-card_9b6702a7.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction à l’IA pour le travail", en: "Introduction à l’IA pour le travail", ar: "Introduction à l’IA pour le travail" },
  },
  "datacamp_introduction_to_google_workspace_with_gemini": {
    socialPath: "/manus-storage/datacamp_introduction_to_google_workspace_with_gemini-social_3f60e076.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_google_workspace_with_gemini-card_e4bcaeab.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction à Google Workspace avec Gemini", en: "Introduction à Google Workspace avec Gemini", ar: "Introduction à Google Workspace avec Gemini" },
  },
  "datacamp_microsoft_copilot_in_powerpoint": {
    socialPath: "/manus-storage/datacamp_microsoft_copilot_in_powerpoint-social_7b976ddb.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_microsoft_copilot_in_powerpoint-card_3a6b4d09.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Microsoft Copilot dans PowerPoint", en: "Microsoft Copilot dans PowerPoint", ar: "Microsoft Copilot dans PowerPoint" },
  },
  "datacamp_microsoft_copilot_in_word": {
    socialPath: "/manus-storage/datacamp_microsoft_copilot_in_word-social_45bcc2c4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_microsoft_copilot_in_word-card_2fd6b542.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Microsoft Copilot dans Word", en: "Microsoft Copilot dans Word", ar: "Microsoft Copilot dans Word" },
  },
  "datacamp_practical_ai_with_google_gemini_and_notebooklm": {
    socialPath: "/manus-storage/datacamp_practical_ai_with_google_gemini_and_notebooklm-social_8807c08b.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_practical_ai_with_google_gemini_and_notebooklm-card_e27f8665.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA pratique avec Google Gemini et NotebookLM", en: "IA pratique avec Google Gemini et NotebookLM", ar: "IA pratique avec Google Gemini et NotebookLM" },
  },
};
