import type { TrainingVisualAsset } from "./trainingVisualAssets";

/** Assets générés à partir du template de marque pour chaque formation. */
export const GENERATED_TRAINING_VISUAL_ASSETS: Record<string, TrainingVisualAsset> = {
  "claude_certified_architect_foundations": {
    socialPath: "/manus-storage/claude_certified_architect_foundations-social_dbcf36cb.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_architect_foundations-card_102969a8.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Architect – Fondations", en: "Claude Certified Architect – Fondations", ar: "Claude Certified Architect – Fondations" },
  },
  "claude_certified_architect_professional": {
    socialPath: "/manus-storage/claude_certified_architect_professional-social_ef27e18e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_architect_professional-card_b7289050.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Architect – Professionnel", en: "Claude Certified Architect – Professionnel", ar: "Claude Certified Architect – Professionnel" },
  },
  "claude_certified_associate_foundations": {
    socialPath: "/manus-storage/claude_certified_associate_foundations-social_126e69c1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_associate_foundations-card_8bd7d289.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Associate – Fondations", en: "Claude Certified Associate – Fondations", ar: "Claude Certified Associate – Fondations" },
  },
  "claude_certified_developer_foundations": {
    socialPath: "/manus-storage/claude_certified_developer_foundations-social_08bbe975.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/claude_certified_developer_foundations-card_b7ea7230.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Certified Developer – Fondations", en: "Claude Certified Developer – Fondations", ar: "Claude Certified Developer – Fondations" },
  },
  "analyse_donnees_reporting_bi_codex": {
    socialPath: "/manus-storage/analyse_donnees_reporting_bi_codex-social_19fceba7.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/analyse_donnees_reporting_bi_codex-card_9f4efd3d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Analyse de données, reporting et BI avec Codex", en: "Analyse de données, reporting et BI avec Codex", ar: "Analyse de données, reporting et BI avec Codex" },
  },
  "datacamp_ai_for_data_analysts": {
    socialPath: "/manus-storage/datacamp_ai_for_data_analysts-social_43b25380.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_data_analysts-card_f286c960.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour les data analysts", en: "L’IA pour les data analysts", ar: "L’IA pour les data analysts" },
  },
  "datacamp_ai_for_finance": {
    socialPath: "/manus-storage/datacamp_ai_for_finance-social_b0111714.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_finance-card_cf602fbb.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour la finance", en: "L’IA pour la finance", ar: "L’IA pour la finance" },
  },
  "datacamp_building_marketing_workflows_with_n8n": {
    socialPath: "/manus-storage/datacamp_building_marketing_workflows_with_n8n-social_a04eea9a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_marketing_workflows_with_n8n-card_cab0801d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des workflows marketing automatisés", en: "Concevoir des workflows marketing automatisés", ar: "Concevoir des workflows marketing automatisés" },
  },
  "datacamp_intermediate_workflow_automation_with_n8n": {
    socialPath: "/manus-storage/datacamp_intermediate_workflow_automation_with_n8n-social_76e99d9a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_intermediate_workflow_automation_with_n8n-card_e4a6b8fb.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Automatisation de workflows avancée", en: "Automatisation de workflows avancée", ar: "Automatisation de workflows avancée" },
  },
  "initiation_automatisation_workflows_n8n": {
    socialPath: "/manus-storage/initiation_automatisation_workflows_n8n-social_770b2c88.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/initiation_automatisation_workflows_n8n-card_6734ac86.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Initiation à l’automatisation de workflows", en: "Initiation à l’automatisation de workflows", ar: "Initiation à l’automatisation de workflows" },
  },
  "ai_finops_cost_engineering_specialist": {
    socialPath: "/manus-storage/ai_finops_cost_engineering_specialist-social_bf4ce6b8.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_finops_cost_engineering_specialist-card_92f4f698.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI FinOps and Cost Engineering Specialist", en: "AI FinOps and Cost Engineering Specialist", ar: "AI FinOps and Cost Engineering Specialist" },
  },
  "ai_governance_compliance_responsible_ai_leader": {
    socialPath: "/manus-storage/ai_governance_compliance_responsible_ai_leader-social_b4f50a13.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_governance_compliance_responsible_ai_leader-card_8e8000c3.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Governance, Compliance and Responsible AI Leader", en: "AI Governance, Compliance and Responsible AI Leader", ar: "AI Governance, Compliance and Responsible AI Leader" },
  },
  "ai_product_management_human_centered_ux_specialist": {
    socialPath: "/manus-storage/ai_product_management_human_centered_ux_specialist-social_5cf6e738.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_product_management_human_centered_ux_specialist-card_c6587265.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Product Management and Human-Centered UX Specialist", en: "AI Product Management and Human-Centered UX Specialist", ar: "AI Product Management and Human-Centered UX Specialist" },
  },
  "ia_pour_les_nuls": {
    socialPath: "/manus-storage/ia_pour_les_nuls-social_43602614.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_pour_les_nuls-card_86634bd9.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA pour les nuls – Initiation", en: "IA pour les nuls – Initiation", ar: "IA pour les nuls – Initiation" },
  },
  "datacamp_building_scalable_agentic_systems": {
    socialPath: "/manus-storage/datacamp_building_scalable_agentic_systems-social_566b1145.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_scalable_agentic_systems-card_6fae1bef.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des systèmes agentiques évolutifs", en: "Concevoir des systèmes agentiques évolutifs", ar: "Concevoir des systèmes agentiques évolutifs" },
  },
  "datacamp_claude_101": {
    socialPath: "/manus-storage/datacamp_claude_101-social_e560a74f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_claude_101-card_9dfdd5f1.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude 101", en: "Claude 101", ar: "Claude 101" },
  },
  "datacamp_claude_code_101": {
    socialPath: "/manus-storage/datacamp_claude_code_101-social_ecd1d4cf.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_claude_code_101-card_dc8ea488.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Code 101", en: "Claude Code 101", ar: "Claude Code 101" },
  },
  "datacamp_claude_code_in_action": {
    socialPath: "/manus-storage/datacamp_claude_code_in_action-social_5169a4b0.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_claude_code_in_action-card_5f9cea2f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Claude Code en action", en: "Claude Code en action", ar: "Claude Code en action" },
  },
  "datacamp_introduction_to_agent_skills": {
    socialPath: "/manus-storage/datacamp_introduction_to_agent_skills-social_7ca6ef46.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_agent_skills-card_80cfae89.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux Agent Skills", en: "Introduction aux Agent Skills", ar: "Introduction aux Agent Skills" },
  },
  "datacamp_introduction_to_claude_models": {
    socialPath: "/manus-storage/datacamp_introduction_to_claude_models-social_7f1b56e5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_claude_models-card_2544328e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux modèles Claude", en: "Introduction aux modèles Claude", ar: "Introduction aux modèles Claude" },
  },
  "datacamp_introduction_to_subagents": {
    socialPath: "/manus-storage/datacamp_introduction_to_subagents-social_463c08ff.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_subagents-card_c4be5329.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux sous-agents", en: "Introduction aux sous-agents", ar: "Introduction aux sous-agents" },
  },
  "datacamp_model_context_protocol_advanced_topics": {
    socialPath: "/manus-storage/datacamp_model_context_protocol_advanced_topics-social_adb9275a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_model_context_protocol_advanced_topics-card_ef67d574.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Sujets avancés sur le Model Context Protocol", en: "Sujets avancés sur le Model Context Protocol", ar: "Sujets avancés sur le Model Context Protocol" },
  },
  "datacamp_software_development_with_claude_code": {
    socialPath: "/manus-storage/datacamp_software_development_with_claude_code-social_d152dc8c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_software_development_with_claude_code-card_2c156609.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développement logiciel avec Claude Code", en: "Développement logiciel avec Claude Code", ar: "Développement logiciel avec Claude Code" },
  },
  "transformation_processus_ia": {
    socialPath: "/manus-storage/transformation_processus_ia-social_833e1542.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/transformation_processus_ia-card_b6657f24.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Transformation des Processus par l'IA", en: "Transformation des Processus par l'IA", ar: "Transformation des Processus par l'IA" },
  },
  "novasavo_automatisation_comptable_ia": {
    socialPath: "/manus-storage/novasavo_automatisation_comptable_ia-social_203c5739.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/novasavo_automatisation_comptable_ia-card_45beeb4e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Automatisation comptable par l’IA", en: "Automatisation comptable par l’IA", ar: "Automatisation comptable par l’IA" },
  },
  "advanced_rag_evaluation_specialist": {
    socialPath: "/manus-storage/advanced_rag_evaluation_specialist-social_0537d52f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/advanced_rag_evaluation_specialist-card_512c163e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Advanced RAG and Evaluation Specialist", en: "Advanced RAG and Evaluation Specialist", ar: "Advanced RAG and Evaluation Specialist" },
  },
  "ai_data_engineering_rag_practitioner": {
    socialPath: "/manus-storage/ai_data_engineering_rag_practitioner-social_56548be7.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_data_engineering_rag_practitioner-card_08cc5811.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Data Engineering and RAG Practitioner", en: "AI Data Engineering and RAG Practitioner", ar: "AI Data Engineering and RAG Practitioner" },
  },
  "ai_production_infrastructure_model_serving_engineer": {
    socialPath: "/manus-storage/ai_production_infrastructure_model_serving_engineer-social_9a03a181.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ai_production_infrastructure_model_serving_engineer-card_fe137574.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "AI Production Infrastructure and Model Serving Engineer", en: "AI Production Infrastructure and Model Serving Engineer", ar: "AI Production Infrastructure and Model Serving Engineer" },
  },
  "datacamp_advanced_ai_assisted_coding_for_developers": {
    socialPath: "/manus-storage/datacamp_advanced_ai_assisted_coding_for_developers-social_e5cf2d9d.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_advanced_ai_assisted_coding_for_developers-card_18fc9ccd.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Programmation assistée par IA avancée pour les développeurs", en: "Programmation assistée par IA avancée pour les développeurs", ar: "Programmation assistée par IA avancée pour les développeurs" },
  },
  "datacamp_ai_agents_with_hugging_face_smolagents": {
    socialPath: "/manus-storage/datacamp_ai_agents_with_hugging_face_smolagents-social_ba50cc68.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_agents_with_hugging_face_smolagents-card_378237b6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des agents IA avec smolagents", en: "Concevoir des agents IA avec smolagents", ar: "Concevoir des agents IA avec smolagents" },
  },
  "datacamp_ai_assisted_coding_for_developers": {
    socialPath: "/manus-storage/datacamp_ai_assisted_coding_for_developers-social_e01e4464.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_assisted_coding_for_developers-card_4af5ac4d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Coder avec l’aide de l’IA pour les développeurs", en: "Coder avec l’aide de l’IA pour les développeurs", ar: "Coder avec l’aide de l’IA pour les développeurs" },
  },
  "datacamp_ai_for_marketing": {
    socialPath: "/manus-storage/datacamp_ai_for_marketing-social_1af22ccf.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_marketing-card_c759c1f3.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA pour le marketing", en: "IA pour le marketing", ar: "IA pour le marketing" },
  },
  "datacamp_ai_for_sales": {
    socialPath: "/manus-storage/datacamp_ai_for_sales-social_742565a7.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_sales-card_781c1d8b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour les ventes", en: "L’IA pour les ventes", ar: "L’IA pour les ventes" },
  },
  "datacamp_building_agentic_workflows_with_llamaindex": {
    socialPath: "/manus-storage/datacamp_building_agentic_workflows_with_llamaindex-social_7f71b6ef.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_agentic_workflows_with_llamaindex-card_9d192b82.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Créer des workflows agentiques avec LlamaIndex", en: "Créer des workflows agentiques avec LlamaIndex", ar: "Créer des workflows agentiques avec LlamaIndex" },
  },
  "datacamp_building_ai_agents_with_crewai": {
    socialPath: "/manus-storage/datacamp_building_ai_agents_with_crewai-social_6cf9b174.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_ai_agents_with_crewai-card_0b4aa246.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Créer des agents d’IA avec CrewAI", en: "Créer des agents d’IA avec CrewAI", ar: "Créer des agents d’IA avec CrewAI" },
  },
  "datacamp_building_ai_agents_with_haystack": {
    socialPath: "/manus-storage/datacamp_building_ai_agents_with_haystack-social_d5154ad5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_building_ai_agents_with_haystack-card_babd661c.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Créer des agents d’IA avec Haystack", en: "Créer des agents d’IA avec Haystack", ar: "Créer des agents d’IA avec Haystack" },
  },
  "datacamp_databricks_with_the_python_sdk": {
    socialPath: "/manus-storage/datacamp_databricks_with_the_python_sdk-social_7ca71015.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_databricks_with_the_python_sdk-card_e7a22e7d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Databricks avec le SDK Python", en: "Databricks avec le SDK Python", ar: "Databricks avec le SDK Python" },
  },
  "datacamp_deploying_ai_into_production_with_fastapi": {
    socialPath: "/manus-storage/datacamp_deploying_ai_into_production_with_fastapi-social_c54c5aab.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_deploying_ai_into_production_with_fastapi-card_3969fb08.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Déployer l’IA en production avec FastAPI", en: "Déployer l’IA en production avec FastAPI", ar: "Déployer l’IA en production avec FastAPI" },
  },
  "datacamp_efficient_ai_model_training_with_pytorch": {
    socialPath: "/manus-storage/datacamp_efficient_ai_model_training_with_pytorch-social_073509fc.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_efficient_ai_model_training_with_pytorch-card_9120cb0b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Entraîner efficacement des modèles d’IA avec PyTorch", en: "Entraîner efficacement des modèles d’IA avec PyTorch", ar: "Entraîner efficacement des modèles d’IA avec PyTorch" },
  },
  "datacamp_end_to_end_rag_with_weaviate": {
    socialPath: "/manus-storage/datacamp_end_to_end_rag_with_weaviate-social_fdaa9800.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_end_to_end_rag_with_weaviate-card_3705cb5d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "RAG de bout en bout avec Weaviate", en: "RAG de bout en bout avec Weaviate", ar: "RAG de bout en bout avec Weaviate" },
  },
  "datacamp_graph_rag_with_langchain_and_neo4j": {
    socialPath: "/manus-storage/datacamp_graph_rag_with_langchain_and_neo4j-social_47469532.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_graph_rag_with_langchain_and_neo4j-card_09a96a74.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Graph RAG avec LangChain et Neo4j", en: "Graph RAG avec LangChain et Neo4j", ar: "Graph RAG avec LangChain et Neo4j" },
  },
  "datacamp_innovating_with_google_cloud_ai": {
    socialPath: "/manus-storage/datacamp_innovating_with_google_cloud_ai-social_68a7638c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_innovating_with_google_cloud_ai-card_1471fe0e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Innover avec Google Cloud AI", en: "Innover avec Google Cloud AI", ar: "Innover avec Google Cloud AI" },
  },
  "datacamp_introduction_to_generative_ai_in_snowflake": {
    socialPath: "/manus-storage/datacamp_introduction_to_generative_ai_in_snowflake-social_16775686.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_generative_ai_in_snowflake-card_76d1993d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA générative dans Snowflake", en: "IA générative dans Snowflake", ar: "IA générative dans Snowflake" },
  },
  "datacamp_introduction_to_model_context_protocol_mcp": {
    socialPath: "/manus-storage/datacamp_introduction_to_model_context_protocol_mcp-social_0968fc09.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_model_context_protocol_mcp-card_81f6f6f4.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction au Model Context Protocol (MCP)", en: "Introduction au Model Context Protocol (MCP)", ar: "Introduction au Model Context Protocol (MCP)" },
  },
  "datacamp_multi_agent_systems_with_langgraph": {
    socialPath: "/manus-storage/datacamp_multi_agent_systems_with_langgraph-social_44888356.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_multi_agent_systems_with_langgraph-card_52d6974b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Systèmes multi-agents avec LangGraph", en: "Systèmes multi-agents avec LangGraph", ar: "Systèmes multi-agents avec LangGraph" },
  },
  "datacamp_multi_modal_models_with_hugging_face": {
    socialPath: "/manus-storage/datacamp_multi_modal_models_with_hugging_face-social_83e7dace.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_multi_modal_models_with_hugging_face-card_026bfe36.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir des modèles multimodaux", en: "Concevoir des modèles multimodaux", ar: "Concevoir des modèles multimodaux" },
  },
  "datacamp_scalable_ai_models_with_pytorch_lightning": {
    socialPath: "/manus-storage/datacamp_scalable_ai_models_with_pytorch_lightning-social_82ffa1fc.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_scalable_ai_models_with_pytorch_lightning-card_f3738c90.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Modèles d’IA évolutifs avec PyTorch Lightning", en: "Modèles d’IA évolutifs avec PyTorch Lightning", ar: "Modèles d’IA évolutifs avec PyTorch Lightning" },
  },
  "datacamp_software_development_with_github_copilot": {
    socialPath: "/manus-storage/datacamp_software_development_with_github_copilot-social_2276362d.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_software_development_with_github_copilot-card_0581861f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développement logiciel avec GitHub Copilot", en: "Développement logiciel avec GitHub Copilot", ar: "Développement logiciel avec GitHub Copilot" },
  },
  "datacamp_software_development_with_windsurf": {
    socialPath: "/manus-storage/datacamp_software_development_with_windsurf-social_b3f23969.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_software_development_with_windsurf-card_c2557e7f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développement logiciel avec Windsurf", en: "Développement logiciel avec Windsurf", ar: "Développement logiciel avec Windsurf" },
  },
  "datacamp_text_to_query_agents_with_mongodb_and_langgraph": {
    socialPath: "/manus-storage/datacamp_text_to_query_agents_with_mongodb_and_langgraph-social_f641c3ac.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_text_to_query_agents_with_mongodb_and_langgraph-card_34ad243b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agents de text-to-query avec MongoDB et LangGraph", en: "Agents de text-to-query avec MongoDB et LangGraph", ar: "Agents de text-to-query avec MongoDB et LangGraph" },
  },
  "datacamp_vibe_coding_with_replit": {
    socialPath: "/manus-storage/datacamp_vibe_coding_with_replit-social_d0c4b3c5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_vibe_coding_with_replit-card_eeb3ed8e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Coder en mode Vibe avec Replit", en: "Coder en mode Vibe avec Replit", ar: "Coder en mode Vibe avec Replit" },
  },
  "full_stack_ai_application_developer": {
    socialPath: "/manus-storage/full_stack_ai_application_developer-social_ddfd7154.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/full_stack_ai_application_developer-card_c5fb9574.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Full-Stack AI Application Developer", en: "Full-Stack AI Application Developer", ar: "Full-Stack AI Application Developer" },
  },
  "huggingface_llm_course": {
    socialPath: "/manus-storage/huggingface_llm_course-social_c05b63fe.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/huggingface_llm_course-card_adf182cf.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Fondamentaux des grands modèles de langage", en: "Fondamentaux des grands modèles de langage", ar: "Fondamentaux des grands modèles de langage" },
  },
  "llm_application_security_red_teaming_specialist": {
    socialPath: "/manus-storage/llm_application_security_red_teaming_specialist-social_1ce46cea.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/llm_application_security_red_teaming_specialist-card_cc426c1e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "LLM Application Security and Red Teaming Specialist", en: "LLM Application Security and Red Teaming Specialist", ar: "LLM Application Security and Red Teaming Specialist" },
  },
  "llmops_ai_observability_engineer": {
    socialPath: "/manus-storage/llmops_ai_observability_engineer-social_c894fb3c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/llmops_ai_observability_engineer-card_91a0933d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "LLMOps and AI Observability Engineer", en: "LLMOps and AI Observability Engineer", ar: "LLMOps and AI Observability Engineer" },
  },
  "open_source_llms_fine_tuning_engineer": {
    socialPath: "/manus-storage/open_source_llms_fine_tuning_engineer-social_baf2a5a5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/open_source_llms_fine_tuning_engineer-card_35892441.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Open-Source LLMs and Fine-Tuning Engineer", en: "Open-Source LLMs and Fine-Tuning Engineer", ar: "Open-Source LLMs and Fine-Tuning Engineer" },
  },
  "datacamp_developing_ai_systems_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_developing_ai_systems_with_the_openai_api-social_35ef95b6.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_developing_ai_systems_with_the_openai_api-card_294116b1.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Développer des systèmes d’IA avec l’API OpenAI", en: "Développer des systèmes d’IA avec l’API OpenAI", ar: "Développer des systèmes d’IA avec l’API OpenAI" },
  },
  "datacamp_introduction_to_embeddings_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_introduction_to_embeddings_with_the_openai_api-social_793b35ac.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_embeddings_with_the_openai_api-card_2ad48c3b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction aux embeddings avec l’API OpenAI", en: "Introduction aux embeddings avec l’API OpenAI", ar: "Introduction aux embeddings avec l’API OpenAI" },
  },
  "datacamp_multi_modal_systems_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_multi_modal_systems_with_the_openai_api-social_54306322.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_multi_modal_systems_with_the_openai_api-card_e4006ac7.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Systèmes multimodaux avec l’API OpenAI", en: "Systèmes multimodaux avec l’API OpenAI", ar: "Systèmes multimodaux avec l’API OpenAI" },
  },
  "datacamp_prompt_engineering_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_prompt_engineering_with_the_openai_api-social_4a67d202.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_prompt_engineering_with_the_openai_api-card_d0bae678.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Prompt Engineering avec l’API OpenAI", en: "Prompt Engineering avec l’API OpenAI", ar: "Prompt Engineering avec l’API OpenAI" },
  },
  "datacamp_working_with_the_openai_api": {
    socialPath: "/manus-storage/datacamp_working_with_the_openai_api-social_4e448f31.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_working_with_the_openai_api-card_307d8b21.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Travailler avec l’API OpenAI", en: "Travailler avec l’API OpenAI", ar: "Travailler avec l’API OpenAI" },
  },
  "datacamp_working_with_the_openai_responses_api": {
    socialPath: "/manus-storage/datacamp_working_with_the_openai_responses_api-social_a82e9351.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_working_with_the_openai_responses_api-card_3e35cbaa.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Utiliser l’API OpenAI Responses", en: "Utiliser l’API OpenAI Responses", ar: "Utiliser l’API OpenAI Responses" },
  },
  "ia_appliquee_metiers_tp__formation_01": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_01-social_ddf1cdfe.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_01-card_34270c6d.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de prospection Google Maps avec scoring automatique", en: "Agent de prospection Google Maps avec scoring automatique", ar: "Agent de prospection Google Maps avec scoring automatique" },
  },
  "ia_appliquee_metiers_tp__formation_02": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_02-social_e1ff1d9d.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_02-card_965713fc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent IA de qualification automatique des leads", en: "Agent IA de qualification automatique des leads", ar: "Agent IA de qualification automatique des leads" },
  },
  "ia_appliquee_metiers_tp__formation_03": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_03-social_d1000fbf.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_03-card_8bab5f19.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent d'enrichissement et qualification automatique dans HubSpot", en: "Agent d'enrichissement et qualification automatique dans HubSpot", ar: "Agent d'enrichissement et qualification automatique dans HubSpot" },
  },
  "ia_appliquee_metiers_tp__formation_04": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_04-social_ce916328.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_04-card_49d4557f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Assistant IA permettant d'interroger HubSpot en langage naturel", en: "Assistant IA permettant d'interroger HubSpot en langage naturel", ar: "Assistant IA permettant d'interroger HubSpot en langage naturel" },
  },
  "ia_appliquee_metiers_tp__formation_05": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_05-social_a777f78c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_05-card_7d434c85.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Prospection quotidienne automatisée avec e-mails personnalisés", en: "Prospection quotidienne automatisée avec e-mails personnalisés", ar: "Prospection quotidienne automatisée avec e-mails personnalisés" },
  },
  "ia_appliquee_metiers_tp__formation_06": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_06-social_0dd7b26f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_06-card_b667023c.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de génération automatique de propositions commerciales", en: "Agent de génération automatique de propositions commerciales", ar: "Agent de génération automatique de propositions commerciales" },
  },
  "ia_appliquee_metiers_tp__formation_07": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_07-social_e53f970a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_07-card_589fcb72.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Équipe de trois agents pour LinkedIn, X et Instagram", en: "Équipe de trois agents pour LinkedIn, X et Instagram", ar: "Équipe de trois agents pour LinkedIn, X et Instagram" },
  },
  "ia_appliquee_metiers_tp__formation_08": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_08-social_61a6def7.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_08-card_487efd45.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent transformant les commentaires sociaux en stratégie de contenu", en: "Agent transformant les commentaires sociaux en stratégie de contenu", ar: "Agent transformant les commentaires sociaux en stratégie de contenu" },
  },
  "ia_appliquee_metiers_tp__formation_09": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_09-social_f78b3a1e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_09-card_070e4e8e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent qui analyse les contenus viraux puis publie automatiquement", en: "Agent qui analyse les contenus viraux puis publie automatiquement", ar: "Agent qui analyse les contenus viraux puis publie automatiquement" },
  },
  "ia_appliquee_metiers_tp__formation_10": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_10-social_1151a7b4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_10-card_3d174403.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agence SEO autonome composée de plusieurs agents", en: "Agence SEO autonome composée de plusieurs agents", ar: "Agence SEO autonome composée de plusieurs agents" },
  },
  "ia_appliquee_metiers_tp__formation_11": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_11-social_3c8c3b41.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_11-card_bbd56fdd.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un agent de support client avec Make.com", en: "Construire un agent de support client avec Make.com", ar: "Construire un agent de support client avec Make.com" },
  },
  "ia_appliquee_metiers_tp__formation_12": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_12-social_a220e61c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_12-card_920cdd78.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir un agent IA de support client", en: "Concevoir un agent IA de support client", ar: "Concevoir un agent IA de support client" },
  },
  "ia_appliquee_metiers_tp__formation_13": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_13-social_5f1416b9.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_13-card_16c7e234.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Chatbot de site web capable de lire le site et la documentation", en: "Chatbot de site web capable de lire le site et la documentation", ar: "Chatbot de site web capable de lire le site et la documentation" },
  },
  "ia_appliquee_metiers_tp__formation_14": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_14-social_847cbe4b.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_14-card_fa760401.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent Zendesk RAG avec base documentaire et mémoire", en: "Agent Zendesk RAG avec base documentaire et mémoire", ar: "Agent Zendesk RAG avec base documentaire et mémoire" },
  },
  "ia_appliquee_metiers_tp__formation_15": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_15-social_8c9bda4c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_15-card_29f4148b.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent e-commerce connecté aux commandes et stocks", en: "Agent e-commerce connecté aux commandes et stocks", ar: "Agent e-commerce connecté aux commandes et stocks" },
  },
  "ia_appliquee_metiers_tp__formation_16": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_16-social_709b668d.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_16-card_a79d5fd6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Piloter Shopify directement par conversation", en: "Piloter Shopify directement par conversation", ar: "Piloter Shopify directement par conversation" },
  },
  "ia_appliquee_metiers_tp__formation_17": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_17-social_6cd2d1ee.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_17-card_c77981af.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un agent de tenue comptable", en: "Construire un agent de tenue comptable", ar: "Construire un agent de tenue comptable" },
  },
  "ia_appliquee_metiers_tp__formation_18": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_18-social_31d66565.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_18-card_c06156e9.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de traitement de factures - tutoriel français", en: "Agent de traitement de factures - tutoriel français", ar: "Agent de traitement de factures - tutoriel français" },
  },
  "ia_appliquee_metiers_tp__formation_19": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_19-social_0aaed042.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_19-card_1382ed70.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Comptabilisation automatique des factures reçues dans Google Drive", en: "Comptabilisation automatique des factures reçues dans Google Drive", ar: "Comptabilisation automatique des factures reçues dans Google Drive" },
  },
  "ia_appliquee_metiers_tp__formation_20": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_20-social_6b62cbfd.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_20-card_18a34c94.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Facturation et relances automatiques des impayés", en: "Facturation et relances automatiques des impayés", ar: "Facturation et relances automatiques des impayés" },
  },
  "ia_appliquee_metiers_tp__formation_21": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_21-social_9398eca1.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_21-card_bbb2d8a8.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Reporting financier mensuel avec détection d'anomalies", en: "Reporting financier mensuel avec détection d'anomalies", ar: "Reporting financier mensuel avec détection d'anomalies" },
  },
  "ia_appliquee_metiers_tp__formation_22": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_22-social_3ed3c3d9.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_22-card_96e13000.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent capable de traiter et classer 1 000 CV", en: "Agent capable de traiter et classer 1 000 CV", ar: "Agent capable de traiter et classer 1 000 CV" },
  },
  "ia_appliquee_metiers_tp__formation_23": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_23-social_d115664d.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_23-card_d99c60bb.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Recrutement avec agents spécialisés selon le poste", en: "Recrutement avec agents spécialisés selon le poste", ar: "Recrutement avec agents spécialisés selon le poste" },
  },
  "ia_appliquee_metiers_tp__formation_24": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_24-social_771f4601.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_24-card_35918b93.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Présélection et entretien comportemental réalisé par un Voice Agent", en: "Présélection et entretien comportemental réalisé par un Voice Agent", ar: "Présélection et entretien comportemental réalisé par un Voice Agent" },
  },
  "ia_appliquee_metiers_tp__formation_25": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_25-social_78a10998.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_25-card_aad8a24e.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Screening des candidats puis planification automatique des entretiens", en: "Screening des candidats puis planification automatique des entretiens", ar: "Screening des candidats puis planification automatique des entretiens" },
  },
  "ia_appliquee_metiers_tp__formation_26": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_26-social_584febdf.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_26-card_c8492686.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Automatiser l'onboarding collaborateur avec Jira, Notion et Gmail", en: "Automatiser l'onboarding collaborateur avec Jira, Notion et Gmail", ar: "Automatiser l'onboarding collaborateur avec Jira, Notion et Gmail" },
  },
  "ia_appliquee_metiers_tp__formation_27": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_27-social_09937869.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_27-card_2d42b424.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent IA qui gère complètement une boîte Gmail", en: "Agent IA qui gère complètement une boîte Gmail", ar: "Agent IA qui gère complètement une boîte Gmail" },
  },
  "ia_appliquee_metiers_tp__formation_28": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_28-social_6ce36d24.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_28-card_ac415122.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Concevoir un agent d’assistance par e-mail", en: "Concevoir un agent d’assistance par e-mail", ar: "Concevoir un agent d’assistance par e-mail" },
  },
  "ia_appliquee_metiers_tp__formation_29": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_29-social_e98baeab.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_29-card_ecedad35.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Transformer des notes vocales Telegram en tâches Notion", en: "Transformer des notes vocales Telegram en tâches Notion", ar: "Transformer des notes vocales Telegram en tâches Notion" },
  },
  "ia_appliquee_metiers_tp__formation_30": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_30-social_309f4588.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_30-card_27af4772.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Assistant exécutif Telegram avec Gmail, Calendar et Notion", en: "Assistant exécutif Telegram avec Gmail, Calendar et Notion", ar: "Assistant exécutif Telegram avec Gmail, Calendar et Notion" },
  },
  "ia_appliquee_metiers_tp__formation_31": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_31-social_012decd9.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_31-card_062635d1.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Compte rendu de réunion vers décisions, tâches Linear et Slack", en: "Compte rendu de réunion vers décisions, tâches Linear et Slack", ar: "Compte rendu de réunion vers décisions, tâches Linear et Slack" },
  },
  "ia_appliquee_metiers_tp__formation_32": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_32-social_a760bad2.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_32-card_7387b351.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un Data Analyst IA conversationnel", en: "Construire un Data Analyst IA conversationnel", ar: "Construire un Data Analyst IA conversationnel" },
  },
  "ia_appliquee_metiers_tp__formation_33": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_33-social_1dd27e6a.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_33-card_dd5a62d8.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Interroger une base MySQL en langage naturel", en: "Interroger une base MySQL en langage naturel", ar: "Interroger une base MySQL en langage naturel" },
  },
  "ia_appliquee_metiers_tp__formation_34": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_34-social_a1bfc22c.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_34-card_bf86b1be.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Construire un agent de recherche Web avec Perplexity", en: "Construire un agent de recherche Web avec Perplexity", ar: "Construire un agent de recherche Web avec Perplexity" },
  },
  "ia_appliquee_metiers_tp__formation_35": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_35-social_4197d09b.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_35-card_eb162471.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent RAG pour analyser les résultats financiers d'entreprises", en: "Agent RAG pour analyser les résultats financiers d'entreprises", ar: "Agent RAG pour analyser les résultats financiers d'entreprises" },
  },
  "ia_appliquee_metiers_tp__formation_36": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_36-social_afed8c85.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_36-card_42a04af6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent permettant de dialoguer avec les fichiers Drive et Supabase", en: "Agent permettant de dialoguer avec les fichiers Drive et Supabase", ar: "Agent permettant de dialoguer avec les fichiers Drive et Supabase" },
  },
  "ia_appliquee_metiers_tp__formation_37": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_37-social_63800eb4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_37-card_708179cc.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent qui compare les clauses d'un contrat à votre playbook juridique", en: "Agent qui compare les clauses d'un contrat à votre playbook juridique", ar: "Agent qui compare les clauses d'un contrat à votre playbook juridique" },
  },
  "ia_appliquee_metiers_tp__formation_38": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_38-social_995a76f7.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_38-card_9a9821d6.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Système multi-agents de revue contractuelle et conformité réglementaire", en: "Système multi-agents de revue contractuelle et conformité réglementaire", ar: "Système multi-agents de revue contractuelle et conformité réglementaire" },
  },
  "ia_appliquee_metiers_tp__formation_39": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_39-social_fb02dd6e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_39-card_63cb0581.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Analyse automatique des risques d'un contrat PDF", en: "Analyse automatique des risques d'un contrat PDF", ar: "Analyse automatique des risques d'un contrat PDF" },
  },
  "ia_appliquee_metiers_tp__formation_40": {
    socialPath: "/manus-storage/ia_appliquee_metiers_tp__formation_40-social_6cec5dd5.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/ia_appliquee_metiers_tp__formation_40-card_7f59ed49.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Agent de classification et routage de documents juridiques", en: "Agent de classification et routage de documents juridiques", ar: "Agent de classification et routage de documents juridiques" },
  },
  "datacamp_ai_for_consulting": {
    socialPath: "/manus-storage/datacamp_ai_for_consulting-social_6f1c67a4.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_consulting-card_1c796ce0.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour le conseil", en: "L’IA pour le conseil", ar: "L’IA pour le conseil" },
  },
  "datacamp_ai_for_human_resources": {
    socialPath: "/manus-storage/datacamp_ai_for_human_resources-social_fb806482.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_ai_for_human_resources-card_da2fc322.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "L’IA pour les ressources humaines", en: "L’IA pour les ressources humaines", ar: "L’IA pour les ressources humaines" },
  },
  "datacamp_gemini_in_gmail": {
    socialPath: "/manus-storage/datacamp_gemini_in_gmail-social_5485fe27.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_gmail-card_2f9d5472.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Gmail", en: "Gemini dans Gmail", ar: "Gemini dans Gmail" },
  },
  "datacamp_gemini_in_google_docs": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_docs-social_4cb3fd80.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_docs-card_d0a23cb0.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Docs", en: "Gemini dans Google Docs", ar: "Gemini dans Google Docs" },
  },
  "datacamp_gemini_in_google_drive": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_drive-social_357cfe3f.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_drive-card_a5292f8f.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Drive", en: "Gemini dans Google Drive", ar: "Gemini dans Google Drive" },
  },
  "datacamp_gemini_in_google_meet": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_meet-social_2fbd8317.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_meet-card_65e56db0.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Meet", en: "Gemini dans Google Meet", ar: "Gemini dans Google Meet" },
  },
  "datacamp_gemini_in_google_sheets": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_sheets-social_11cd3b3e.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_sheets-card_cb360f01.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Sheets", en: "Gemini dans Google Sheets", ar: "Gemini dans Google Sheets" },
  },
  "datacamp_gemini_in_google_slides": {
    socialPath: "/manus-storage/datacamp_gemini_in_google_slides-social_e6b998f2.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_gemini_in_google_slides-card_d19783aa.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Gemini dans Google Slides", en: "Gemini dans Google Slides", ar: "Gemini dans Google Slides" },
  },
  "datacamp_introduction_to_ai_for_work": {
    socialPath: "/manus-storage/datacamp_introduction_to_ai_for_work-social_58832a81.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_ai_for_work-card_d0be3495.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction à l’IA pour le travail", en: "Introduction à l’IA pour le travail", ar: "Introduction à l’IA pour le travail" },
  },
  "datacamp_introduction_to_google_workspace_with_gemini": {
    socialPath: "/manus-storage/datacamp_introduction_to_google_workspace_with_gemini-social_be8011b6.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_introduction_to_google_workspace_with_gemini-card_6beed187.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Introduction à Google Workspace avec Gemini", en: "Introduction à Google Workspace avec Gemini", ar: "Introduction à Google Workspace avec Gemini" },
  },
  "datacamp_microsoft_copilot_in_powerpoint": {
    socialPath: "/manus-storage/datacamp_microsoft_copilot_in_powerpoint-social_926e1141.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_microsoft_copilot_in_powerpoint-card_99579eae.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Microsoft Copilot dans PowerPoint", en: "Microsoft Copilot dans PowerPoint", ar: "Microsoft Copilot dans PowerPoint" },
  },
  "datacamp_microsoft_copilot_in_word": {
    socialPath: "/manus-storage/datacamp_microsoft_copilot_in_word-social_1af1c5f2.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_microsoft_copilot_in_word-card_848ba002.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "Microsoft Copilot dans Word", en: "Microsoft Copilot dans Word", ar: "Microsoft Copilot dans Word" },
  },
  "datacamp_practical_ai_with_google_gemini_and_notebooklm": {
    socialPath: "/manus-storage/datacamp_practical_ai_with_google_gemini_and_notebooklm-social_70709091.png",
    socialWidth: 1200,
    socialHeight: 630,
    cardPath: "/api/assets/datacamp_practical_ai_with_google_gemini_and_notebooklm-card_70aa6234.png",
    cardWidth: 1200,
    cardHeight: 900,
    alt: { fr: "IA pratique avec Google Gemini et NotebookLM", en: "IA pratique avec Google Gemini et NotebookLM", ar: "IA pratique avec Google Gemini et NotebookLM" },
  },
};
